web:
  config:
    defaultUserId: 7f9c095ee0ed43ba85d6f6b3d533285c

server:
  port: 8090

spring:
  redis:
    database: 0
    host: 39.105.102.17
    port: 6379
    jedis:
      pool:
        max-active: 100
        max-idle: 100
        min-idle: 10
        max-wait: 1000ms
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.105.102.17:3306/epsms?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 96777
    #配置连接池
    type: com.alibaba.druid.pool.DruidDataSource
    # 初始化大小，最小，最大
    initialSize: 1
    minIdle: 3
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 合并多个DruidDataSource的监控数据
      #useGlobalDataSourceStat: true

      #jpa:
      #  hibernate:
      #    ddl-auto: update
      #    naming:
      #数据库，表字段命名是驼峰命名法（UserID）,Spring data jpa 自动更新之后是 user_id, 表字段不对照，
      # PhysicalNamingStrategyStandardImpl 无修改命名
    # SpringPhysicalNamingStrategy 遇到大写字母 加”_”的命名
    #  physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    # show-sql: true
    # database: mysql

    #mybatis:
    #config-location: classpath:mybatis/mybatis-config.xml
    #mapper-locations: classpath:mybatis/mapper/*.xml
    #type-aliases-package: com.dygstudio.my.entity
    #configuration:
    #map-underscore-to-camel-case: true

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  type-aliases-package: com.dygstudio.epsms.service.entity
  mapper-locations: classpath:mybatis/mapper/*.xml